[package]
name = "quick-compress"
version = "0.1.0"
edition = "2024"
authors = ["Emanuel Binimelis <c.binimelis@alumno.um.edu.ar>"]
description = "Fast, native Linux utility to compress and convert images, audio, and video for chat and web"
license = "GPL-3.0-or-later"
repository = "https://github.com/EmaBilibili/quick-compress"

[dependencies]
libadwaita = { version = "0.7", features = ["v1_6"] }
gtk4 = { version = "0.9", features = ["v4_16"] }
image = "0.25"
